;Smileys for MRA protocol

Name    = "MRA"
Author  = "CHEF-KOCH
Date    = "05.04.2011"
Version = "1.0"
SelectionSize = 30,30
ButtonSmiley = "BUTTON"

;============================ Классические ============================

Smiley="smiles/smiles/smile.gif",			0,		"<###20###img010> :)",								":)"
Smiley="smiles/smiles/blink.gif",			0,		"<###20###img011> ;)",								";)"
Smiley="smiles/smiles/laughter.gif",		0,		"<###20###img012> :-))",							":-))"
Smiley="smiles/smiles/bee.gif",				0,		"<###20###img013> ;-P",								";-P"
Smiley="smiles/smiles/coolguy.gif",			0,		"<###20###img014> 8-)",								"8-)"
Smiley="smiles/smiles/biggrin.gif",			0,		"<###20###img015> :-D",								":-D"
Smiley="smiles/smiles/pig.gif",				0,		"<###20###img016> }:o)",							"}:o)"
Smiley="smiles/smiles/bazilio.gif",			0,		"<###20###img017> $-)",								"$-)"
Smiley="smiles/smiles/hm.gif",				0,		"<###20###img018> :-'",								":-'"
Smiley="smiles/smiles/disappointed.gif",	0,		"<###20###img019> :-(",								":-("
Smiley="smiles/smiles/tears.gif",			0,		"<###20###img020> 8-(",								"8-("
Smiley="smiles/smiles/cry.gif",				0,		"<###20###img021> :'(",								":'("
Smiley="smiles/smiles/crocodile.gif",		0,		"<###20###img022> :''()",							":''()"
Smiley="smiles/smiles/really.gif",			0,		"<###20###img023> S:-o",							"S:-o"
Smiley="smiles/smiles/oo.gif",				0,		"<###20###img024> (:-o",							"(:-o""
Smiley="smiles/smiles/amazed.gif",			0,		"<###20###img025> 8-0",								"8-0"
Smiley="smiles/smiles/aaa.gif",				0,		"<###20###img026> 8-[o]",							"8-[o]"
Smiley="smiles/smiles/bullshit.gif",		0,		"<###20###img027> ):-p",							"):-p"
Smiley="smiles/smiles/angry.gif",			0,		"<###20###img028> ):-(",							"):-("
Smiley="smiles/smiles/rrr.gif",				0,		"<###20###img029> ):-$",							"):-$"
Smiley="smiles/smiles/zloradstvo.gif",		0,		"<###20###img030> ):-D",							"):-D"
Smiley="smiles/smiles/biganger.gif",		0,		"<###20###img031> :-E",								":-E"
Smiley="smiles/smiles/devil.gif",			0,		"<###20###img032> :devil: :Чертенок:",				"Чертенок"
Smiley="smiles/smiles/vampire.gif",			0,		"<###20###img033> :vampire: :Вампирчик:",			"Вампирчик"
Smiley="smiles/smiles/plug.gif",			0,		"<###20###img034> :-][",							":-]["
Smiley="smiles/smiles/detzl.gif",			0,		"<###20###img035> :-|",								":-|"
Smiley="smiles/smiles/sceptic.gif",			0,		"<###20###img036> B-j",								"B-j"
Smiley="smiles/smiles/shy.gif",				0,		"<###20###img037> :~o",								":~o"
Smiley="smiles/smiles/ass.gif",				0,		"<###20###img038> (_I_)",							"(_I_)"
Smiley="smiles/smiles/heart.gif",			0,		"<###20###img039> :heart: :Сердце:",				"Сердце"
Smiley="smiles/smiles/kiss.gif",			0,		"<###20###img040> :-*",								":-*"
Smiley="smiles/smiles/sleepy.gif",			0,		"<###20###img041> :sleepy: :Сплю:",					"Сплю"

;============================ Жесты ============================

Smiley="smiles/hands/live.gif",			0,		"<###20###img000> :cool: :Отлично!:",							"Отлично!"
Smiley="smiles/hands/victory.gif",		0,		"<###20###img001> :viva: :Peace!:",								"Peace!"
Smiley="smiles/hands/ok.gif",			0,		"<###20###img002> :ok: :OK:",									"OK"
Smiley="smiles/hands/koza_left.gif",	0,		"<###20###img003> :yo: :Левая%%__%%%%''%%коза%%''%%:",			"Левая ''коза''"
Smiley="smiles/hands/koza_right.gif",	0,		"<###20###img004> :yo2: :Правая%%__%%%%''%%коза%%''%%:",		"Правая ''коза''"
Smiley="smiles/hands/die.gif",			0,		"<###20###img005> :suxx: :Плохо:",								"Плохо"
Smiley="smiles/hands/think.gif",		0,		"<###20###img006> :think: :Внимание!:",							"Внимание!"
Smiley="smiles/hands/kukes.gif",		0,		"<###20###img007> :figu: :Фига:",								"Фига"
Smiley="smiles/hands/fist.gif",			0,		"<###20###img008> :kulak: :Кулак:",								"Кулак"
Smiley="smiles/hands/fuck.gif",			0,		"<###20###img009> :fuck: :Отвали!:",							"Отвали!"

;============================ Анимированные ============================

Smiley="smiles/animated/angel.gif",		0,		"<SMILE>id=200%%__%%alt=':Ангелочек:'</SMILE> :Ангелочек:",											"Ангелочек"
Smiley="smiles/animated/appl.gif",		0,		"<SMILE>id=201%%__%%alt=':Аплодисменты:'</SMILE> :Аплодисменты:",									"Аплодисменты"
Smiley="smiles/animated/beauty.gif",	0,		"<SMILE>id=202%%__%%alt=':Красотка:'</SMILE> :Красотка:",											"Красотка"
Smiley="smiles/animated/beer.gif",		0,		"<SMILE>id=203%%__%%alt=':Пиво:'</SMILE> :Пиво:",													"Пиво"
Smiley="smiles/animated/book.gif",		0,		"<SMILE>id=204%%__%%alt=':Читаю:'</SMILE> :Читаю:",													"Читаю"
Smiley="smiles/animated/could.gif",		0,		"<SMILE>id=205%%__%%alt=':Мёрзну:'</SMILE> :Мёрзну:",												"Мёрзну"
Smiley="smiles/animated/cry.gif",		0,		"<SMILE>id=206%%__%%alt=':Рыдаю:'</SMILE> :Рыдаю:",													"Рыдаю"
Smiley="smiles/animated/dance.gif",		0,		"<SMILE>id=207%%__%%alt=':Танцую:'</SMILE> :Танцую:",												"Танцую"
Smiley="smiles/animated/devil.gif",		0,		"<SMILE>id=208%%__%%alt=':Чертовски%%__%%злюсь:'</SMILE> :Чертовски%%__%%злюсь:",					"Чертовски злюсь"
Smiley="smiles/animated/eat.gif",		0,		"<SMILE>id=209%%__%%alt=':Жую:'</SMILE> :Жую:",														"Жую"
Smiley="smiles/animated/fight.gif",		0,		"<SMILE>id=210%%__%%alt=':Побью:'</SMILE> :Побью:",													"Побью"
Smiley="smiles/animated/fingal.gif",	0,		"<SMILE>id=211%%__%%alt=':Побили:'</SMILE> :Побили:",												"Побили"
Smiley="smiles/animated/flowr.gif",		0,		"<SMILE>id=212%%__%%alt=':Дарю%%__%%цветочек:'</SMILE> :Дарю%%__%%цветочек:",						"Дарю цветочек"
Smiley="smiles/animated/gg.gif",		0,		"<SMILE>id=213%%__%%alt=':Смеюсь:'</SMILE> :Смеюсь:",												"Смеюсь"
Smiley="smiles/animated/gg2.gif",		0,		"<SMILE>id=214%%__%%alt=':Смеюсь%%__%%и%%__%%плачу:'</SMILE> :Смеюсь%%__%%и%%__%%плачу:",			"Смеюсь и плачу"
Smiley="smiles/animated/gift.gif",		0,		"<SMILE>id=215%%__%%alt=':Подарок:'</SMILE> :Подарок:",												"Подарок"
Smiley="smiles/animated/hungry.gif",	0,		"<SMILE>id=216%%__%%alt=':Ворчу:'</SMILE> :Ворчу:",													"Ворчу"
Smiley="smiles/animated/kiss.gif",		0,		"<SMILE>id=217%%__%%alt=':Целую:'</SMILE> :Целую:",													"Целую"
Smiley="smiles/animated/love.gif",		0,		"<SMILE>id=218%%__%%alt=':Люблю:'</SMILE> :Люблю:",													"Люблю"
Smiley="smiles/animated/pistolet.gif",	0,		"<SMILE>id=219%%__%%alt=':Застрелю:'</SMILE> :Застрелю:"											"Застрелю"
Smiley="smiles/animated/poison.gif",	0,		"<SMILE>id=220%%__%%alt=':Выпей%%__%%яду:'</SMILE> :Выпей%%__%%яду:",								"Выпей яду"
Smiley="smiles/animated/rainbow.gif",	0,		"<SMILE>id=221%%__%%alt=':Лучезарно:'</SMILE> :Лучезарно:",											"Лучезарно"
Smiley="smiles/animated/red.gif",		0,		"<SMILE>id=222%%__%%alt=':Смущаюсь:'</SMILE> :Смущаюсь:",											"Смущаюсь"
Smiley="smiles/animated/sad.gif",		0,		"<SMILE>id=223%%__%%alt=':Расстраиваюсь:'</SMILE> :Расстраиваюсь:",									"Расстраиваюсь"
Smiley="smiles/animated/sing.gif",		0,		"<SMILE>id=224%%__%%alt=':Пою:'</SMILE> :Пою:",														"Пою"
Smiley="smiles/animated/skuka.gif",		0,		"<SMILE>id=225%%__%%alt=':Скучаю:'</SMILE> :Скучаю:",												"Скучаю"
Smiley="smiles/animated/sleep.gif",		0,		"<SMILE>id=226%%__%%alt=':Засыпаю:'</SMILE> :Засыпаю:",												"Засыпаю"
Smiley="smiles/animated/smile.gif",		0,		"<SMILE>id=227%%__%%alt=':Улыбаюсь:'</SMILE> :Улыбаюсь:"											"Улыбаюсь"
Smiley="smiles/animated/tongue.gif",	0,		"<SMILE>id=228%%__%%alt=':Показываю%%__%%язык:'</SMILE> :Показываю%%__%%язык:",						"Показываю язык"
Smiley="smiles/animated/victory.gif",	0,		"<SMILE>id=229%%__%%alt=':Peace!:'</SMILE> :Peace!:",												"Peace!"
Smiley="smiles/animated/wonder.gif",	0,		"<SMILE>id=230%%__%%alt=':Удивляюсь:'</SMILE> :Удивляюсь:",											"Удивляюсь"
Smiley="smiles/animated/blew.gif",		0,		"<SMILE>id=231%%__%%alt=':Тошнит:'</SMILE> :Тошнит:",												"Тошнит"

;============================ Продвинутые ============================

Smiley="smiles/static/smiles_murmansk_03.gif",	0,		"<SMILE>id=300%%__%%alt=':Улыбаюсь:'</SMILE> <SMILE>id='300'%%__%%alt=':Улыбаюсь:'</SMILE> :Улыбаюсь:",											"Улыбаюсь"
Smiley="smiles/static/smiles_murmansk_05.gif",	0,		"<SMILE>id=301%%__%%alt=':Злорадствую:'</SMILE> <SMILE>id='301'%%__%%alt=':Злорадствую:'</SMILE> :Злорадствую:",										"Злорадствую"
Smiley="smiles/static/smiles_murmansk_07.gif",	0,		"<SMILE>id=302%%__%%alt=':Радуюсь:'</SMILE> <SMILE>id='302'%%__%%alt=':Радуюсь:'</SMILE> :Радуюсь:",												"Радуюсь"
Smiley="smiles/static/smiles_murmansk_09.gif",	0,		"<SMILE>id=303%%__%%alt=':Старичок:'</SMILE> <SMILE>id='303'%%__%%alt=':Старичок:'</SMILE> :Старичок:",											"Старичок"
Smiley="smiles/static/smiles_murmansk_11.gif",	0,		"<SMILE>id=304%%__%%alt=':Свирепствую:'</SMILE> <SMILE>id='304'%%__%%alt=':Свирепствую:'</SMILE> :Свирепствую:",										"Свирепствую"
Smiley="smiles/static/smiles_murmansk_13.gif",	0,		"<SMILE>id=305%%__%%alt=':Пугаюсь:'</SMILE> <SMILE>id='305'%%__%%alt=':Пугаюсь:'</SMILE> :Пугаюсь:",												"Пугаюсь"
Smiley="smiles/static/smiles_murmansk_21.gif",	0,		"<SMILE>id=306%%__%%alt=':Показываю%%__%%язык:'</SMILE> <SMILE>id='306'%%__%%alt=':Показываю%%__%%язык:'</SMILE> :Показываю%%__%%язык:",						"Показываю язык"
Smiley="smiles/static/smiles_murmansk_22.gif",	0,		"<SMILE>id=307%%__%%alt=':Умник:'</SMILE> <SMILE>id='307'%%__%%alt=':Умник:'</SMILE> :Умник:",													"Умник"
Smiley="smiles/static/smiles_murmansk_23.gif",	0,		"<SMILE>id=308%%__%%alt=':Алкоголик:'</SMILE> <SMILE>id='308'%%__%%alt=':Алкоголик:'</SMILE> :Алкоголик:",											"Алкоголик"
Smiley="smiles/static/smiles_murmansk_24.gif",	0,		"<SMILE>id=309%%__%%alt=':Вояка:'</SMILE> <SMILE>id='309'%%__%%alt=':Вояка:'</SMILE> :Вояка:",													"Вояка"
Smiley="smiles/static/smiles_murmansk_25.gif",	0,		"<SMILE>id=310%%__%%alt=':Удивляюсь:'</SMILE> <SMILE>id='310'%%__%%alt=':Удивляюсь:'</SMILE> :Удивляюсь:",											"Удивляюсь"
Smiley="smiles/static/smiles_murmansk_26.gif",	0,		"<SMILE>id=311%%__%%alt=':Чертовски%%__%%злюсь:'</SMILE> <SMILE>id='311'%%__%%alt=':Чертовски%%__%%злюсь:'</SMILE> :Чертовски%%__%%злюсь:",					"Чертовски злюсь"
Smiley="smiles/static/smiles_murmansk_33.gif",	0,		"<SMILE>id=312%%__%%alt=':Расстраиваюсь:'</SMILE> <SMILE>id='312'%%__%%alt=':Расстраиваюсь:'</SMILE> :Расстраиваюсь:",									"Расстраиваюсь"
Smiley="smiles/static/smiles_murmansk_34.gif",	0,		"<SMILE>id=313%%__%%alt=':Панк:'</SMILE> <SMILE>id='313'%%__%%alt=':Панк:'</SMILE> :Панк:",													"Панк"
Smiley="smiles/static/smiles_murmansk_35.gif",	0,		"<SMILE>id=314%%__%%alt=':Лопну%%__%%от%%__%%смеха:'</SMILE> <SMILE>id='314'%%__%%alt=':Лопну%%__%%от%%__%%смеха:'</SMILE> :Лопну%%__%%от%%__%%смеха:",			"Лопну от смеха"
Smiley="smiles/static/smiles_murmansk_36.gif",	0,		"<SMILE>id=315%%__%%alt=':Подмигиваю:'</SMILE> <SMILE>id='315'%%__%%alt=':Подмигиваю:'</SMILE> :Подмигиваю:",										"Подмигиваю"
Smiley="smiles/static/smiles_murmansk_37.gif",	0,		"<SMILE>id=316%%__%%alt=':Думаю:'</SMILE> <SMILE>id='316'%%__%%alt=':Думаю:'</SMILE> :Думаю:",													"Думаю"
Smiley="smiles/static/smiles_murmansk_38.gif",	0,		"<SMILE>id=317%%__%%alt=':Люблю:'</SMILE> <SMILE>id='317'%%__%%alt=':Люблю:'</SMILE> :Люблю:",													"Люблю"
Smiley="smiles/static/smiles_murmansk_45.gif",	0,		"<SMILE>id=318%%__%%alt=':Подавлен:'</SMILE> <SMILE>id='318'%%__%%alt=':Подавлен:'</SMILE> :Подавлен:",											"Подавлен"
Smiley="smiles/static/smiles_murmansk_46.gif",	0,		"<SMILE>id=319%%__%%alt=':Рыдаю:'</SMILE> <SMILE>id='319'%%__%%alt=':Рыдаю:'</SMILE> :Рыдаю:",													"Рыдаю"
Smiley="smiles/static/smiles_murmansk_47.gif",	0,		"<SMILE>id=320%%__%%alt=':Сейчас%%__%%расплачусь:'</SMILE> <SMILE>id='320'%%__%%alt=':Сейчас%%__%%расплачусь:'</SMILE> :Сейчас%%__%%расплачусь:",				"Сейчас расплачусь"
Smiley="smiles/static/smiles_murmansk_48.gif",	0,		"<SMILE>id=321%%__%%alt=':Злюсь:'</SMILE> <SMILE>id='321'%%__%%alt=':Злюсь:'</SMILE> :Злюсь:",													"Злюсь"
Smiley="smiles/static/smiles_murmansk_49.gif",	0,		"<SMILE>id=322%%__%%alt=':Тошнит:'</SMILE> <SMILE>id='322'%%__%%alt=':Тошнит:'</SMILE> :Тошнит:",												"Тошнит"
Smiley="smiles/static/smiles_murmansk_50.gif",	0,		"<SMILE>id=323%%__%%alt=':Сумасшествие:'</SMILE> <SMILE>id='323'%%__%%alt=':Сумасшествие:'</SMILE> :Сумасшествие:",									"Сумасшествие"
Smiley="smiles/static/smiles_murmansk_57.gif",	0,		"<SMILE>id=324%%__%%alt=':Целую:'</SMILE> <SMILE>id='324'%%__%%alt=':Целую:'</SMILE> :Целую:",													"Целую"
Smiley="smiles/static/smiles_murmansk_58.gif",	0,		"<SMILE>id=325%%__%%alt=':Поцеловали:'</SMILE> <SMILE>id='325'%%__%%alt=':Поцеловали:'</SMILE> :Поцеловали:",										"Поцеловали"
Smiley="smiles/static/smiles_murmansk_59.gif",	0,		"<SMILE>id=326%%__%%alt=':Красотка:'</SMILE> <SMILE>id='326'%%__%%alt=':Красотка:'</SMILE> :Красотка:",											"Красотка"
Smiley="smiles/static/smiles_murmansk_60.gif",	0,		"<SMILE>id=327%%__%%alt=':Ангелочек:'</SMILE> <SMILE>id='327'%%__%%alt=':Ангелочек:'</SMILE> :Ангелочек:",											"Ангелочек"
Smiley="smiles/static/smiles_murmansk_61.gif",	0,		"<SMILE>id=328%%__%%alt=':Подозрительно:'</SMILE> <SMILE>id='328'%%__%%alt=':Подозрительно:'</SMILE> :Подозрительно:",									"Подозрительно"
Smiley="smiles/static/smiles_murmansk_62.gif",	0,		"<SMILE>id=329%%__%%alt=':Жую:'</SMILE> <SMILE>id='329'%%__%%alt=':Жую:'</SMILE> :Жую:",														"Жую"
Smiley="smiles/static/smiles_murmansk_69.gif",	0,		"<SMILE>id=330%%__%%alt=':Смущаюсь:'</SMILE> <SMILE>id='330'%%__%%alt=':Смущаюсь:'</SMILE> :Смущаюсь:",											"Смущаюсь"
Smiley="smiles/static/smiles_murmansk_70.gif",	0,		"<SMILE>id=331%%__%%alt=':Стыдно:'</SMILE> <SMILE>id='331'%%__%%alt=':Стыдно:'</SMILE> :Стыдно:",												"Стыдно"

;============================ Колобки ============================

Smiley="smiles/set03/angel.gif",					0,		"<SMILE>id=400%%__%%alt=':Ангелочек:'</SMILE> :Ангелочек:",									"Ангелочек"
Smiley="smiles/set03/bad.gif",						0,		"<SMILE>id=401%%__%%alt=':Тошнит:'</SMILE> :Тошнит:",										"Тошнит"
Smiley="smiles/set03/biggrin.gif",					0,		"<SMILE>id=402%%__%%alt=':Улыбка%%__%%до%%__%%ушей:'</SMILE> :Улыбка%%__%%до%%__%%ушей:",	"Улыбка до ушей"
Smiley="smiles/set03/blum.gif",						0,		"<SMILE>id=403%%__%%alt=':Дразнюсь:'</SMILE> :Дразнюсь:",									"Дразнюсь"
Smiley="smiles/set03/blush.gif",					0,		"<SMILE>id=404%%__%%alt=':Смущаюсь:'</SMILE> :Смущаюсь:",									"Смущаюсь"
Smiley="smiles/set03/cray.gif",						0,		"<SMILE>id=405%%__%%alt=':Рыдаю:'</SMILE> :Рыдаю:",											"Рыдаю"
Smiley="smiles/set03/crazy.gif",					0,		"<SMILE>id=406%%__%%alt=':Сумасшествие:'</SMILE> :Сумасшествие:",							"Сумасшествие"
Smiley="smiles/set03/dance.gif",					0,		"<SMILE>id=407%%__%%alt=':Танцую:'</SMILE> :Танцую:",										"Танцую"
Smiley="smiles/set03/diablo.gif",					0,		"<SMILE>id=408%%__%%alt=':Чертовски%%__%%злюсь:'</SMILE> :Чертовски%%__%%злюсь:",			"Чертовски злюсь"
Smiley="smiles/set03/dirol.gif",					0,		"<SMILE>id=409%%__%%alt=':Я%%__%%круче:'</SMILE> :Я%%__%%круче:",							"Я круче"
Smiley="smiles/set03/drinks.gif",					0,		"<SMILE>id=410%%__%%alt=':Пиво:'</SMILE> :Пиво:",											"Пиво"
Smiley="smiles/set03/fool.gif",						0,		"<SMILE>id=411%%__%%alt=':Ты%%__%%что!:'</SMILE> :Ты%%__%%что!:",							"Ты что!"
Smiley="smiles/set03/give_rose.gif",				0,		"<SMILE>id=412%%__%%alt=':Дарю%%__%%цветочек:'</SMILE> :Дарю%%__%%цветочек:",				"Дарю цветочек"
Smiley="smiles/set03/good.gif",						0,		"<SMILE>id=413%%__%%alt=':Ок!:'</SMILE> :Ок!:",												"Ок!"
Smiley="smiles/set03/kiss_mini.gif",				0,		"<SMILE>id=414%%__%%alt=':Целую:'</SMILE> :Целую:",											"Целую"
Smiley="smiles/set03/man_in_love.gif",				0,		"<SMILE>id=415%%__%%alt=':Поцеловали:'</SMILE> :Поцеловали:",								"Поцеловали"
Smiley="smiles/set03/mocking.gif",					0,		"<SMILE>id=416%%__%%alt=':Хихикаю:'</SMILE> :Хихикаю:",										"Хихикаю"
Smiley="smiles/set03/music.gif",					0,		"<SMILE>id=417%%__%%alt=':Слушаю%%__%%музыку:'</SMILE> :Слушаю%%__%%музыку:",				"Слушаю музыку"
Smiley="smiles/set03/nea.gif",						0,		"<SMILE>id=418%%__%%alt=':Не-а:'</SMILE> :Не-а:",											"Не-а"
Smiley="smiles/set03/pardon.gif",					0,		"<SMILE>id=419%%__%%alt=':Извини:'</SMILE> :Извини:",										"Извини"
Smiley="smiles/set03/rofl.gif",						0,		"<SMILE>id=420%%__%%alt=':Лопну%%__%%от%%__%%смеха:'</SMILE> :Лопну%%__%%от%%__%%смеха:",	"Лопну от смеха"
Smiley="smiles/set03/rolleyes.gif",					0,		"<SMILE>id=421%%__%%alt=':Мечтаю:'</SMILE> :Мечтаю:",										"Мечтаю"
Smiley="smiles/set03/sad.gif",						0,		"<SMILE>id=422%%__%%alt=':В%%__%%печали:'</SMILE> :В%%__%%печали:",							"В печали"
Smiley="smiles/set03/scratch_one-s_head.gif",		0,		"<SMILE>id=423%%__%%alt=':Надо%%__%%подумать:'</SMILE> :Надо%%__%%подумать:",				"Надо подумать"
Smiley="smiles/set03/shok.gif",						0,		"<SMILE>id=424%%__%%alt=':Ой,%%__%%ё:'</SMILE> :Ой,%%__%%ё:",								"Ой, ё"
Smiley="smiles/set03/shout.gif",					0,		"<SMILE>id=425%%__%%alt=':Кричу:'</SMILE> :Кричу:",											"Кричу"
Smiley="smiles/set03/smile.gif",					0,		"<SMILE>id=426%%__%%alt=':Улыбаюсь:'</SMILE> :Улыбаюсь:",									"Улыбаюсь"
Smiley="smiles/set03/unknw.gif",					0,		"<SMILE>id=427%%__%%alt=':Не%%__%%знаю:'</SMILE> :Не%%__%%знаю:",							"Не знаю"
Smiley="smiles/set03/wacko2.gif",					0,		"<SMILE>id=428%%__%%alt=':В%%__%%изнеможении:'</SMILE> :В%%__%%изнеможении:",				"В изнеможении"
Smiley="smiles/set03/wink.gif",						0,		"<SMILE>id=429%%__%%alt=':Подмигиваю:'</SMILE> :Подмигиваю:",								"Подмигиваю"
Smiley="smiles/set03/yahoo.gif",					0,		"<SMILE>id=430%%__%%alt=':Уррра!:'</SMILE> :Уррра!:",										"Уррра!"
Smiley="smiles/set03/boian.gif",					0,		"<SMILE>id=431%%__%%alt=':Бойан:'</SMILE> :Бойан:",											"Бойан"
Smiley="smiles/set03/kut.gif",						0,		"<SMILE>id=432%%__%%alt=':Ктулху:'</SMILE> :Ктулху:",										"Ктулху"

;====================================== Большие ===========================

Smiley="smiles/set04/s001.gif", 0, "<SMILE>id=501%%__%%alt=':Ура!:'</SMILE> :Ура!:", "Ура!"
Smiley="smiles/set04/s002.gif", 0, "<SMILE>id=502%%__%%alt=':Привет!:'</SMILE> :Привет!:", "Привет!"
Smiley="smiles/set04/s003.gif",	0, "<SMILE>id=503%%__%%alt=':Кушаю:'</SMILE> :Кушаю:", "Кушаю"
Smiley="smiles/set04/s004.gif", 0, "<SMILE>id=504%%__%%alt=':Танцую:'</SMILE> :Танцую:", "Танцую"
Smiley="smiles/set04/s005.gif", 0, "<SMILE>id=505%%__%%alt=':Целую:'</SMILE> :Целую:", "Целую"
Smiley="smiles/set04/s006.gif",	0, "<SMILE>id=506%%__%%alt=':Пока!:'</SMILE> :Пока!:", "Пока!"
Smiley="smiles/set04/s007.gif", 0, "<SMILE>id=507%%__%%alt=':Слушаю%%__%%музыку:'</SMILE> :Слушаю%%__%%музыку:", "Слушаю музыку"
Smiley="smiles/set04/s008.gif",	0, "<SMILE>id=508%%__%%alt=':Помоги:'</SMILE> :Помоги:", "Помоги"
Smiley="smiles/set04/s009.gif",	0, "<SMILE>id=509%%__%%alt=':Бабло!:'</SMILE> :Бабло!:", "Бабло!"
Smiley="smiles/set04/s010.gif", 0, "<SMILE>id=510%%__%%alt=':Да!:'</SMILE> :Да!:", "Да!"
Smiley="smiles/set04/s011.gif",	0, "<SMILE>id=511%%__%%alt=':Головой%%__%%об%%__%%стену:'</SMILE> :Головой%%__%%об%%__%%стену:", "Головой об стену"
Smiley="smiles/set04/s012.gif",	0, "<SMILE>id=512%%__%%alt=':В%%__%%атаку!:'</SMILE> :В%%__%%атаку!:",	"В атаку!"
Smiley="smiles/set04/s013.gif",	0, "<SMILE>id=513%%__%%alt=':Пацанчик:'</SMILE> :Пацанчик:", "Пацанчик"
Smiley="smiles/set04/s014.gif",	0, "<SMILE>id=514%%__%%alt=':Нет!:'</SMILE> :Нет!:", "Нет!"
Smiley="smiles/set04/s015.gif", 0, "<SMILE>id=515%%__%%alt=':Мир!:'</SMILE> :Мир!:", "Мир!"
Smiley="smiles/set04/s016.gif",	0, "<SMILE>id=516%%__%%alt=':Дракончик:'</SMILE> :Дракончик:", "Дракончик"

Smiley="smiles/set05/s001.gif",	0, "<SMILE>id=601%%__%%alt=':Лопну%%__%%от%%__%%смеха:'</SMILE> :Лопну%%__%%от%%__%%смеха:",	"Лопну от смеха"
Smiley="smiles/set05/s002.gif",	0, "<SMILE>id=602%%__%%alt=':Чертовски%%__%%злюсь:'</SMILE> :Чертовски%%__%%злюсь:",	"Чертовси злюсь"
Smiley="smiles/set05/s003.gif",	0, "<SMILE>id=603%%__%%alt=':Секрет:'</SMILE> :Секрет:",	"Секрет"
Smiley="smiles/set05/s004.gif",	0, "<SMILE>id=604%%__%%alt=':В%%__%%изнеможении:'</SMILE> :В%%__%%изнеможении:",	"В изнеможении"
Smiley="smiles/set05/s005.gif",	0, "<SMILE>id=605%%__%%alt=':Влюблён:'</SMILE> :Влюблён:",	"Влюблён"
Smiley="smiles/set05/s006.gif",	0, "<SMILE>id=606%%__%%alt=':Целую:'</SMILE> :Целую:",	"Целую"
Smiley="smiles/set05/s007.gif",	0, "<SMILE>id=607%%__%%alt=':Обида:'</SMILE> :Обида:",	"Обида"
Smiley="smiles/set05/s008.gif",	0, "<SMILE>id=608%%__%%alt=':Устал:'</SMILE> :Устал:",	"Устал"
Smiley="smiles/set05/s009.gif",	0, "<SMILE>id=609%%__%%alt=':Подмигиваю:'</SMILE> :Подмигиваю:",	"Подмигиваю"
Smiley="smiles/set05/s010.gif",	0, "<SMILE>id=610%%__%%alt=':Гадость:'</SMILE> :Гадость:",	"Гадость"
Smiley="smiles/set05/s011.gif",	0, "<SMILE>id=611%%__%%alt=':Виноват:'</SMILE> :Виноват:",	"Виноват"
Smiley="smiles/set05/s012.gif",	0, "<SMILE>id=612%%__%%alt=':Любовь:'</SMILE> :Любовь:",	"Любовь"
Smiley="smiles/set05/s013.gif",	0, "<SMILE>id=613%%__%%alt=':Разочарование:'</SMILE> :Разочарование:",	"Разочарование"
Smiley="smiles/set05/s014.gif",	0, "<SMILE>id=614%%__%%alt=':Сплю:'</SMILE> :Сплю:",	"Сплю"
Smiley="smiles/set05/s015.gif",	0, "<SMILE>id=615%%__%%alt=':Ой,%%__%%ё:'</SMILE> :Ой,%%__%%ё:",	"Ой, ё"
Smiley="smiles/set05/s016.gif",	0, "<SMILE>id=616%%__%%alt=':Прыгаю:'</SMILE> :Прыгаю:",	"Прыгаю"
Smiley="smiles/set05/s017.gif",	0, "<SMILE>id=617%%__%%alt=':Требую:'</SMILE> :Требую:",	"Требую"
Smiley="smiles/set05/s018.gif",	0, "<SMILE>id=618%%__%%alt=':Тошнит:'</SMILE> :Тошнит:",	"Тошнит"
Smiley="smiles/set05/s019.gif",	0, "<SMILE>id=619%%__%%alt=':Дарю%%__%%цветочек:'</SMILE> :Дарю%%__%%цветоче:",	"Дарю цветочек"
Smiley="smiles/set05/s020.gif",	0, "<SMILE>id=620%%__%%alt=':Подозреваю:'</SMILE> :Подозреваю:",	"Подозреваю"

;============================ Флешки ============================

Smiley="flash/mult_kiss.png",		0,		"<SMILE>id=flash_0%%__%%alt='Поцелуй'</SMILE> <SMILE>id=flash_0%%__%%alt=':Поцелуй:'</SMILE>",																	"Поцелуй"
Smiley="flash/mult_beer.png",		0,		"<SMILE>id=flas_1%%__%%alt='Пивка?;)'</SMILE> <SMILE>id=flas_1%%__%%alt=':Пивка?;):'</SMILE>",																	"Пивка?;)"
Smiley="flash/mult_bored.png",		0,		"<SMILE>id=flash_2%%__%%alt='Задолбал!'</SMILE> <SMILE>id=flash_2%%__%%alt=':Задолбал!:'</SMILE>",																"Задолбал!"
Smiley="flash/mult_dog.png",		0,		"<SMILE>id=flash_3%%__%%alt='Хочу%%__%%к%%__%%тебе!'</SMILE> <SMILE>id=flash_3%%__%%alt=':Хочу%%__%%к%%__%%тебе!:'</SMILE>",									"Хочу к тебе!"
Smiley="flash/mult_girl.png",		0,		"<SMILE>id=flash_4%%__%%alt='Хны...!'</SMILE> <SMILE>id=flash_4%%__%%alt=':Хны...!:'</SMILE>",																	"Хны...!"
Smiley="flash/mult_hangover.png",	0,		"<SMILE>id=flash_5%%__%%alt='Отходняк...'</SMILE> <SMILE>id=flash_5%%__%%alt=':Отходняк...:'</SMILE>",															"Отходняк..."
Smiley="flash/mult_heart.png",		0,		"<SMILE>id=flash_6%%__%%alt='Сердце'</SMILE> <SMILE>id=flash_6%%__%%alt=':Сердце:'</SMILE>",																	"Сердце"
Smiley="flash/mult_laugh.png",		0,		"<SMILE>id=flash_7%%__%%alt='Жжёшь!'</SMILE> <SMILE>id=flash_7%%__%%alt=':Жжёшь!:'</SMILE>",																	"Жжёшь!"
Smiley="flash/mult_maddog.png",		0,		"<SMILE>id=flash_8%%__%%alt='А%%__%%я%%__%%сошла%%__%%с%%__%%ума...'</SMILE> <SMILE>id=flash_8%%__%%alt=':А%%__%%я%%__%%сошла%%__%%с%%__%%ума...:'</SMILE>",	"А я сошла с ума..."
Smiley="flash/mult_roses.png",		0,		"<SMILE>id=flash_9%%__%%alt='Миллион%%__%%алых%%__%%роз!'</SMILE> <SMILE>id=flash_9%%__%%alt=':Миллион%%__%%алых%%__%%роз!:'</SMILE>",							"Миллион алых роз!"
Smiley="flash/mult_shoot.png",		0,		"<SMILE>id=flash_10%%__%%alt='Пристрелю!'</SMILE> <SMILE>id=flash_10%%__%%alt=':Пристрелю!:'</SMILE>",															"Пристрелю!"
Smiley="flash/mult_working.png",	0,		"<SMILE>id=flash_11%%__%%alt='Я%%__%%занят'</SMILE> <SMILE>id=flash_11%%__%%alt=':Я%%__%%занят:'</SMILE>",														"Я занят"
Smiley="flash/kot_cool.png",		0,		"<SMILE>id=flash_12%%__%%alt='Круто!'</SMILE> <SMILE>id=flash_12%%__%%alt=':Круто!:'</SMILE>",															  "Круто!"
Smiley="flash/kot_goodbye.png",		0,		"<SMILE>id=flash_13%%__%%alt='Пока-пока'</SMILE> <SMILE>id=flash_13%%__%%alt=':Пока-пока:'</SMILE>",														 "Пока-пока"
Smiley="flash/kot_spasibo.png",		0,		"<SMILE>id=flash_14%%__%%alt='Спасибо!'</SMILE> <SMILE>id=flash_14%%__%%alt=':Спасибо!:'</SMILE>",															"Спасибо!"
Smiley="flash/kot_nedutza.png",		0,		"<SMILE>id=flash_15%%__%%alt='Не%%__%%дуться!'</SMILE> <SMILE>id=flash_15%%__%%alt=':Не%%__%%дуться!:'</SMILE>",												   "Не дуться!"
Smiley="flash/kot_obida.png",		0,		"<SMILE>id=flash_16%%__%%alt='Обидели'</SMILE> <SMILE>id=flash_16%%__%%alt=':Обидели:'</SMILE>",														   "Обидели"
Smiley="flash/kot_wow.png",			0,		"<SMILE>id=flash_17%%__%%alt='Ух%%__%%ты!'</SMILE> <SMILE>id=flash_17%%__%%alt=':Ух%%__%%ты!:'</SMILE>",													   "Ух ты!"

Smiley="flash/bad_cold.png",		0,		"<SMILE>id=flash_20%%__%%alt='Болею'</SMILE> <SMILE>id=flash_20%%__%%alt=':Болею:'</SMILE>",														     "Болею"
Smiley="flash/information.png",		0,		"<SMILE>id=flash_21%%__%%alt='Взрыв%%__%%мозга'</SMILE> <SMILE>id=flash_21%%__%%alt=':Взрыв%%__%%мозга:'</SMILE>",													"Взрыв мозга"
Smiley="flash/joy.png",      		0,	    "<SMILE>id=flash_22%%__%%alt='Радость'</SMILE>            <SMILE>id=flash_22%%__%%alt=':Радость:'</SMILE>",                                                               "Радость"  
Smiley="flash/krizis.png",		    0,		"<SMILE>id=flash_23%%__%%alt='Голяк'</SMILE> <SMILE>id=flash_23%%__%%alt=':Голяк:'</SMILE>",														"Голяк"
Smiley="flash/missyou.png",		    0,		"<SMILE>id=flash_24%%__%%alt='Скучаю'</SMILE> <SMILE>id=flash_24%%__%%alt=':Скучаю:'</SMILE>",														"Скучаю"
Smiley="flash/tank.png",		    0,		"<SMILE>id=flash_25%%__%%alt='Прорвемся!'</SMILE> <SMILE>id=flash_25%%__%%alt=':Прорвемся!:'</SMILE>",														"Прорвемся!"

