//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define ID_FIRSTICON                    1
#define IDDEL                           3
#define IDEDIT                          4
#define IDI_ICQ                         101
#define IDD_ICQACCOUNT                  102
#define IDD_ASKAUTH                     103
#define IDD_LOGINPW                     104
#define IDD_ACCMGRUI                    105
#define IDD_OPT_ICQFEATURES             107
#define IDS_IDENTIFY                    108
#define IDI_PRIVACY                     111
#define IDD_OPT_ICQPRIVACY              111
#define IDI_DOT                         112
#define IDI_CHECK                       113
#define IDI_LIST                        114
#define IDI_ADD1                        116
#define IDI_ADD2                        117
#define IDI_ADD3                        118
#define IDI_ADD4                        119
#define IDI_ADD5                        120
#define IDI_SCAN                        121
#define IDI_START                       122
#define IDI_PAUSE                       123
#define IDI_STOP                        124
#define IDI_HIDDEN                      125
#define IDI_DC                          128
#define IDI_SERVER_IGNORE				129
#define IDI_INCOGNITO_R                 130
#define IDI_AUTH                        131
#define IDD_OPT_POPUPS2                 131
#define IDI_GRANT                       132
#define IDI_REMOVE                      133
#define IDI_SET_VIS                     134
#define IDI_SET_INVIS                   135
#define IDI_SERVLIST_ADD                136
#define IDD_TZER                        137
#define IDI_SEND_TZER                   138
#define IDI_SERVLIST                    139
#define IDD_ICQ_CAPS_LIST               140
#define IDD_CONFIRM                     151
#define IDD_OPT_ICQ                     152
#define ID_LASTICON                     199
#define IDI_XSTATUS1                    201
#define IDI_XSTATUS2                    202
#define IDI_XSTATUS3                    203
#define IDI_XSTATUS4                    204
#define IDI_XSTATUS5                    205
#define IDI_XSTATUS6                    206
#define IDI_XSTATUS7                    207
#define IDI_XSTATUS8                    208
#define IDI_XSTATUS9                    209
#define IDI_XSTATUS10                   210
#define IDI_XSTATUS11                   211
#define IDI_XSTATUS12                   212
#define IDI_XSTATUS13                   213
#define IDI_XSTATUS14                   214
#define IDI_XSTATUS15                   215
#define IDI_XSTATUS16                   216
#define IDI_XSTATUS17                   217
#define IDI_XSTATUS18                   218
#define IDI_XSTATUS19                   219
#define IDI_XSTATUS20                   220
#define IDI_XSTATUS21                   221
#define IDI_XSTATUS22                   222
#define IDI_XSTATUS23                   223
#define IDI_XSTATUS24                   224
#define IDI_XSTATUS25                   225
#define IDI_XSTATUS26                   226
#define IDI_XSTATUS27                   227
#define IDI_XSTATUS28                   228
#define IDI_XSTATUS29                   229
#define IDI_XSTATUS30                   230
#define IDI_XSTATUS31                   231
#define IDI_XSTATUS32                   232
#define IDI_XSTATUS33                   233
#define IDI_XSTATUS34                   234
#define IDI_XSTATUS35                   236
#define IDI_XSTATUS36                   236
#define IDI_XSTATUS37                   237
#define IDD_INFO_ICQ                    240
#define IDD_ICQADVANCEDSEARCH           242
#define IDD_OPT_ICQCONTACTS             252
#define IDD_ICQUPLOADLIST               253
#define IDD_SETXSTATUS                  256
#define IDI_TZER1                       257
#define IDI_TZER2                       258
#define IDI_TZER3                       259
#define IDI_TZER4                       260
#define IDI_TZER5                       261
#define IDI_TZER6                       262
#define IDI_TZER7                       263
#define IDI_TZER8                       264
#define IDI_TZER9                       265
#define IDI_TZER10                      266
#define IDI_TZER11                      267
#define IDI_TZER12                      268
#define IDD_PWCONFIRM                   300
#define IDD_INFO_CHANGEINFO             301
#define IDD_OPT_POPUPS                  400
#define IDD_INFO_ICQ_CLIENT             401
#define IDD_OPT_ICQ_CLIENT_ID           403
#define IDD_ICQ_SRV_LIST                404
#define IDD_OPT_ICQFEATURES2            405
#define IDD_ICQ_REG_UIN                 406
#define IDD_OPT_ICQ_EVENTS              407
#define IDC_TZER_COMBO                  408
#define IDD_OPT_ASD                     408
#define IDC_TZER_NAME                   409
#define IDC_POPUPS_ENABLED              410
#define IDC_POPUPS_LOG_ENABLED          411
#define IDC_POPUP_LOG0_TEXTCOLOR        420
#define IDC_POPUP_LOG1_TEXTCOLOR        421
#define IDC_POPUP_LOG2_TEXTCOLOR        422
#define IDC_POPUP_LOG3_TEXTCOLOR        423
#define IDC_POPUP_SPAM_TEXTCOLOR        425
#define IDC_POPUP_UNKNOWN_TEXTCOLOR     426
#define IDC_POPUP_LOG0_BACKCOLOR        430
#define IDC_POPUP_LOG1_BACKCOLOR        431
#define IDC_POPUP_LOG2_BACKCOLOR        432
#define IDC_POPUP_LOG3_BACKCOLOR        433
#define IDC_POPUP_SPAM_BACKCOLOR        435
#define IDC_POPUP_UNKNOWN_BACKCOLOR     436
#define IDC_POPUP_LOG0_TIMEOUT          440
#define IDC_POPUP_LOG1_TIMEOUT          441
#define IDC_POPUP_LOG2_TIMEOUT          442
#define IDC_POPUP_LOG3_TIMEOUT          443
#define IDC_POPUP_SPAM_TIMEOUT          444
#define IDC_POPUP_UNKNOWN_TIMEOUT       445
#define IDC_USEWINCOLORS                450
#define IDC_USESYSICONS                 451
#define IDC_PREVIEW                     455
#define IDC_POPUP_LOG4_TEXTCOLOR        456
#define IDC_POPUP_LOG5_TEXTCOLOR        457
#define IDC_POPUP_LOG4_BACKCOLOR        458
#define IDC_POPUP_LOG5_BACKCOLOR        459
#define IDC_POPUP_LOG4_TIMEOUT          460
#define IDC_POPUP_LOG5_TIMEOUT          461
#define IDC_POPUP_LOG6_BACKCOLOR        462
#define IDC_POPUP_LOG6_TEXTCOLOR        463
#define IDC_POPUP_LOG6_TIMEOUT          464
#define IDC_POPUP_CLIENT_CHANGE_BACKCOLOR 465
#define IDC_POPUP_CLIENT_CHANGE_TEXTCOLOR 466
#define IDC_POPUP_CLIENT_CHANGE_TIMEOUT 467
#define IDC_POPUP_INFO_REQUEST_BACKCOLOR 468
#define IDC_POPUP_INFO_REQUEST_TEXTCOLOR 469
#define IDC_POPUP_INFO_REQUEST_TIMEOUT  470
#define IDC_POPUP_IGNORECHECK_BACKCOLOR 471
#define IDC_POPUP_IGNORECHECK_TEXTCOLOR 472
#define IDC_POPUP_IGNORECHECK_TIMEOUT   473
#define IDC_POPUP_REMOVE_HIMSELF_BACKCOLOR 477
#define IDC_POPUP_REMOVE_HIMSELF_TEXTCOLOR 478
#define IDC_POPUP_REMOVE_HIMSELF_TIMEOUT 479
#define IDC_POPUP_AUTH_BACKCOLOR        480
#define IDC_POPUP_AUTH_TEXTCOLOR        481
#define IDC_POPUP_AUTH_TIMEOUT          482
#define IDC_POPUP_XUPDATER_BACKCOLOR    483
#define IDC_POPUP_XUPDATER_TEXTCOLOR    484
#define IDC_POPUP_XUPDATER_TIMEOUT      485
#define IDC_LOG                         1001
#define IDI_EXPANDSTRINGEDIT            1001
#define IDC_SAVEPASS                    1004
#define IDC_RETRXSTATUS                 1005
#define IDC_FLAGSTEXT                   1008
#define IDC_SECURE                      1009
#define IDC_USEGATEWAY                  1010
#define IDC_UTFENABLE                   1010
#define IDC_XTITLE                      1010
#define IDC_FLAGS                       1010
#define IDC_SECURE2                     1010
#define IDC_SSL                         1010
#define IDC_XMSG                        1011
#define IDC_KEEPALIVE                   1011
#define IDC_UTFALL                      1012
#define IDC_UTFSTATIC                   1013
#define IDC_UTFCODEPAGE                 1014
#define IDC_PW                          1015
#define IDC_TEMPVISIBLE                 1015
#define IDC_REGISTER                    1016
#define IDC_EDITAUTH                    1017
#define IDC_LOGINPW                     1018
#define IDC_INSTRUCTION                 1019
#define IDC_PASSWORD                    1020
#define IDC_SUPTIME                     1020
#define IDC_DCENABLE                    1020
#define IDC_DCPASSIVE                   1021
#define IDC_OLDPASS                     1021
#define IDC_DCICON                      1022
#define IDC_ICQNUM                      1022
#define IDC_RETRIEVE                    1024
#define IDC_CHANGEID                    1027
#define IDC_IDSTATIC                    1028
#define IDC_HIDE_ID                     1029
#define IDC_HIDEID                      1029
#define IDC_AIMENABLE                   1030
#define IDC_GETSTATUS                   1030
#define IDC_TITLEICON                   1031
#define IDC_BUTTON1                     1032
#define IDC_FORCEREFRESH                1032
#define IDC_PICTURE                     1032
#define IDC_REG                         1032
#define IDC_REGUIN                      1032
#define IDC_POPUPS_OPTIONS              1032
#define IDC_OK                          1032
#define IDC_ASDOPTIONS                  1032
#define IDC_CAPSBOX                     1032
#define IDC_VERSION_CHECKBOX            1034
#define IDC_CLIST                       1035
#define IDC_KILLUNKNOWN                 1038
#define IDC_XSTATUSENABLE               1040
#define IDC_NOTE_POPUP_ENABLE           1040
#define IDC_XSTATUSAUTO                 1041
#define IDC_WARN_POPUP_ENABLE           1041
#define IDC_XSTATUSRESET                1042
#define IDC_ERROR_POPUP_ENABLE          1042
#define IDC_RTF                         1043
#define IDC_FATAL_POPUP_ENABLE          1043
#define IDC_TRY_NEXT                    1043
#define IDC_AUTOCHANGE                  1043
#define IDC_ADDTEMP                     1043
#define IDC_TZER                        1043
#define IDC_LOG_REMOVE_HISTORY          1043
#define IDC_UINPOPUP                    1043
#define IDC_DETECT_VIA_STATUS_MESSAGE   1043
#define IDC_CUSTOM_CAP                  1044
#define IDC_SPAM_POPUP_ENABLE           1044
#define IDC_CHECK4                      1044
#define IDC_DETECT_VIA_ZTRAZ            1044
#define IDC_DETECT_VIA_XTRAZ            1044
#define IDC_USRCHKPOS                   1044
#define IDC_TMPSNDADDED                 1044
#define IDC_KILLSPAMBOTS                1045
#define IDC_LIST1                       1045
#define IDC_CLIENTCAPS                  1045
#define IDC_WAS_FOUND_POPUP_ENABLE      1045
#define IDC_SERVERS                     1045
#define IDC_DETECT_VIA_URL              1045
#define IDC_CAPABILITIES                1045
#define IDC_TMPREQAUTH                  1045
#define IDC_CLIENTICON                  1046
#define IDC_SCAN_POPUP_ENABLE           1046
#define IDC_DETECT_UNAUTHORIZED         1046
#define IDC_REMOVE_TEMP                 1046
#define IDC_TIMESTAMPS                  1047
#define IDC_UNKNOWN_POPUP_ENABLE        1047
#define IDC_DETECT_VIA_AUTH             1047
#define IDC_EMAIL                       1048
#define IDC_ICON_POS_TEXT               1048
#define IDC_VIS_POPUP_ENABLE            1048
#define IDC_PICTURE_CONTENT             1049
#define IDC_NEWUIN_PASS                 1051
#define IDC_NICK                        1053
#define IDC_NEWUININFO                  1053
#define IDC_UIN_IMAGE                   1054
#define IDC_REPLACEXTEXT                1055
#define IDC_SET_VERSION                 1057
#define IDC_FORCEXSTATUS                1057
#define IDC_CUSTCAPEDIT                 1058
#define IDC_CUSTCAPSTATIC               1059
#define IDC_GENDER                      1060
#define IDADD                           1060
#define IDC_CITY                        1061
#define IDCCLOSE                        1061
#define IDC_STATE                       1062
#define IDC_EDIT_SERVER                 1062
#define IDC_COUNTRY                     1063
#define IDC_EDIT_PORT                   1063
#define IDC_DELETE_TMP_CONTACTS         1064
#define IDC_ADD_TMP_CONTACTS            1065
#define IDC_COMPANY                     1066
#define IDC_GROUP                       1066
#define IDC_TMP_CONTACTS_GROUP          1066
#define IDC_DEPARTMENT                  1067
#define IDC_LOG_IGNORECHECK_HISTORY     1067
#define IDC_SHOW_AUTH                   1067
#define IDC_CLIENTC_CHANGE_POPUP        1067
#define IDC_CLIENT_CHANGE_POPUP         1067
#define IDC_XSTUPDATE                   1067
#define IDC_ASD_FOR_OFFLINE             1067
#define IDC_EDIT1                       1068
#define IDC_FILEPATH                    1068
#define IDC_XSTUPDATERATE               1068
#define IDC_CAPL_EDIT                   1068
#define IDC_POSITION                    1069
#define IDC_BROWSE                      1069
#define IDC_LOG_CHECKSTATUS_FILE        1070
#define IDC_LOG_CHECKSTATUS_HISTORY     1071
#define IDC_LOG_CLIENTCHANGE_FILE       1072
#define IDC_LOG_CLIENTCHANGE_HISTORY    1073
#define IDC_LOG_AUTH_FILE               1074
#define IDC_LOG_AUTH_HISTORY            1075
#define IDC_LOG_TO_HCONTACT_HISTORY     1076
#define IDC_NOPSD_FOR_HIDDEN            1076
#define IDC_VIS_POPUP_FOR_NOT_ON_LIST   1076
#define IDC_POPUP_FOR_NOTONLIST         1076
#define IDC_X                           1076
#define IDC_XSTNONSTD                   1076
#define IDC_INCUSER                     1077
#define IDC_POPUP_FOR_IGNORED           1077
#define IDC_INCGLOBAL                   1078
#define IDC_POPUP_FOR_HIDDEN            1078
#define IDC_FAKEWARNING                 1079
#define IDC_REQUEST_LOG_FILE            1080
#define IDC_LOG_REQUEST_FILE            1080
#define IDC_LOG_REQUEST_HISTORY         1081
#define IDC_LOG_ASD_FILE                1082
#define IDC_DC_ICON_POS_TEXT            1083
#define IDC_LOG_ASD_HISTORY             1083
#define IDC_HTTPUSERAGENT               1084
#define IDC_COMBO1                      1085
#define IDC_ENIFMIR                     1086
#define IDC_INSTATUSMENU                1086
#define IDC_ENIFMIRCBX                  1087
#define IDC_INMAINMENU                  1087
#define IDC_                            1088
#define IDI_TZER                        1088
#define IDC_TZER_ICON                   1088
#define IDC_ANIMATE1                    1089
#define IDC_CAPL_ADD                    1090
#define IDC_CAPL_MODIFY                 1091
#define IDC_CAPL_DELETE                 1092
#define IDC_IP                          1094
#define IDC_QIP_STATUS_POS_TEXT         1095
#define IDC_LOG_READXSTATUS_FILE        1096
#define IDC_LOG_READXSTATUS_HISTORY     1097
#define IDC_UINSTATIC                   1122
#define IDC_UIN                         1123
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_ICQSERVER                   1171
#define IDC_ICQPORT                     1172
#define IDC_VERSION                     1179
#define IDC_XSTATUS_ICON_POS            1180
#define IDC_QIP_STATUS_ICON_POS         1181
#define IDC_DC_ICON_POS                 1183
#define IDC_DC_ICON_POS2                1184
#define IDC_WHITERECT                   1220
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_REALIP                      1230
#define IDC_RECONNECTREQD               1239
#define IDC_OFFLINETOENABLE             1240
#define IDC_PORT                        1249
#define IDC_MIRVER                      1251
#define IDC_ONLINESINCE                 1252
#define IDC_SYSTEMUPTIME                1253
#define IDC_IDLETIME                    1254
#define IDC_STATUS                      1255
#define IDC_STATUS2                     1256
#define IDC_ICQ_STATUS                  1256
#define IDC_QIP_STATUS                  1257
#define IDC_SLOWSEND                    1301
#define IDC_ONLYSERVERACKS              1302
#define IDC_LOGLEVEL                    1331
#define IDC_LEVELDESCR                  1332
#define IDC_NOERRMULTI                  1333
#define IDC_STICQGROUP                  1374
#define IDC_ASD                         1380
#define IDC_XSTATUS_SHOW                1381
#define IDC_STEALTHRQST                 1382
#define IDC_NOASD                       1383
#define IDC_PSD                         1384
#define IDC_LOGSELFREM                  1385
#define IDC_LOG_REMOVE_FILE             1385
#define IDC_POPSELFREM                  1386
#define IDC_IGNCHECKLOG                 1387
#define IDC_LOG_IGNORECHECK_FILE        1387
#define IDC_INFOREQUEST_POPUP           1387
#define IDC_INFO_REQUEST_POPUP          1387
#define IDC_IGNCHECKPOP                 1388
#define IDC_ASDSTARTUP                  1389
#define IDC_POPAUTH                     1389
#define IDC_CHECKITEM                   1390
#define IDC_POPXUPDATER                 1390
#define IDC_QIPSTATUS_SHOW              1391
#define IDC_POPCLOSEWND                 1392
#define IDC_READXSTPOPUP                1393
#define IDC_AGERANGE                    1410
#define IDC_MARITALSTATUS               1411
#define IDC_KEYWORDS                    1412
#define IDC_LANGUAGE                    1414
#define IDC_WORKFIELD                   1421
#define IDC_PASTCAT                     1422
#define IDC_PASTKEY                     1423
#define IDC_INTERESTSCAT                1424
#define IDC_INTERESTSKEY                1425
#define IDC_ORGANISATION                1426
#define IDC_ORGKEYWORDS                 1427
#define IDC_OTHERGROUP                  1429
#define IDC_ONLINEONLY                  1430
#define IDC_HOMEPAGECAT                 1431
#define IDC_HOMEPAGEKEY                 1432
#define IDC_SUMMARYGROUP                1434
#define IDC_WORKGROUP                   1435
#define IDC_LOCATIONGROUP               1436
#define IDC_BACKGROUNDGROUP             1437
#define IDC_NEWUINLINK                  1438
#define IDC_LOOKUPLINK                  1439
#define IDC_NEWAIMLINK                  1440
#define IDC_SERVERBOX                   1472
#define IDC_UPLOADNOW                   1521
#define IDC_GROUPS                      1522
#define IDC_ALLGROUPS                   1526
#define IDC_VISIBILITY                  1527
#define IDC_IGNORE                      1528
#define IDC_ENABLE                      1529
#define IDC_LOADFROMSERVER              1530
#define IDC_BIGGERAVATARS               1531
#define IDC_ADDSERVER                   1532
#define IDC_SAVETOSERVER                1533
#define IDC_ADDSERVER2                  1534
#define IDC_SERVERADD                   1534
#define IDC_ENABLEAVATARS               1536
#define IDC_AUTOLOADAVATARS             1537
#define IDC_IGNORECHECK                 1537
#define IDC_STRICTAVATARCHECK           1539
#define IDC_WEBAWARE                    1546
#define IDC_DCALLOW_ANY                 1547
#define IDC_DCALLOW_CLIST               1548
#define IDC_DCALLOW_AUTH                1549
#define IDC_PUBLISHPRIMARY              1550
#define IDC_ADD_ANY                     1551
#define IDC_ADD_AUTH                    1552
#define IDC_STATUSMSG_CLIST             1553
#define IDC_STATUSMSG_VISIBLE           1554
#define IDC_STATIC_NOTONLINE            1555
#define IDC_STATIC_DC2                  1556
#define IDC_STATIC_DC1                  1557
#define IDC_STATIC_CLIST                1558
#define IDC_NOSTATUSREPLY               1559
#define IDC_CONFIRMATION                1560
#define IDC_SET_VERSION_RANGE           1561
#define IDC_AUTH_IGNORE                 1562
#define IDC_SAVE                        1600
#define IDC_LIST                        1601
#define IDC_UPLOADING                   1602
#define IDC_TITLE                       1603
#define IDC_DESC                        1604

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
